#include "GCodeWriter.h"
#include <iomanip>
#include <cmath>

namespace fdm {

// 计算两点间距离
static float Dist(const Vec2& a, const Vec2& b) {
    float dx = b.x - a.x, dy = b.y - a.y;
    return std::sqrt(dx * dx + dy * dy);
}

// 计算挤出量 E：length * lineWidth * layerHeight / (π * (filamentDiameter/2)²)
static float CalcE(float length, float lineWidth, float layerHeight, float filamentDiameter) {
    float area = lineWidth * layerHeight;
    float filArea = 3.14159265f * (filamentDiameter * 0.5f) * (filamentDiameter * 0.5f);
    return length * area / filArea;
}

std::string GenerateGCode(const std::vector<SliceLayer>& layers, const SliceParams& params)
{
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(4);

    float totalE = 0.0f;
    float lastX = 0, lastY = 0;

    // ── 头部 ──
    ss << "; Generated by AMLabSlicer FDM Engine\n";
    ss << "; Layers: " << layers.size() << "\n";
    ss << "G21 ; mm\n";
    ss << "G90 ; absolute positioning\n";
    ss << "M82 ; absolute extrusion\n";
    ss << "M104 S" << (int)params.nozzleTemp << " ; set nozzle temp\n";
    ss << "M140 S" << (int)params.bedTemp << " ; set bed temp\n";
    ss << "M109 S" << (int)params.nozzleTemp << " ; wait nozzle temp\n";
    ss << "M190 S" << (int)params.bedTemp << " ; wait bed temp\n";
    ss << "G28 ; home all\n";
    ss << "G92 E0 ; reset extruder\n";
    ss << "\n";

    for (const auto& layer : layers)
    {
        float speed = (layer.layerIndex == 0) ? params.speedLayer0 : params.speedPrint;
        float lh = (layer.layerIndex == 0) ? params.initialLayerHeight : params.layerHeight;

        ss << ";LAYER:" << layer.layerIndex << "\n";
        ss << "G0 Z" << layer.z << " F600\n";

        // 风扇（第一层不开）
        if (layer.layerIndex == 1)
            ss << "M106 S" << (int)(params.fanSpeed * 2.55f) << "\n";

        // ── 打印外壁轮廓 ──
        for (const auto& contour : layer.outerContours)
        {
            if (contour.empty()) continue;

            // 移动到轮廓起点
            ss << "G0 X" << contour[0].x << " Y" << contour[0].y
               << " F" << (int)(params.speedTravel * 60) << "\n";

            if (params.retractionEnable)
            {
                totalE -= params.retractionAmount; // 取消回抽
                ss << "G1 E" << totalE << " F" << (int)(params.retractionSpeed * 60) << "\n";
            }

            lastX = contour[0].x;
            lastY = contour[0].y;

            for (size_t i = 1; i < contour.size(); ++i)
            {
                float dist = Dist({lastX, lastY}, contour[i]);
                float e = CalcE(dist, params.lineWidth, lh, params.filamentDiameter);
                totalE += e;

                ss << "G1 X" << contour[i].x << " Y" << contour[i].y
                   << " E" << totalE << " F" << (int)(speed * 60) << "\n";

                lastX = contour[i].x;
                lastY = contour[i].y;
            }

            // 闭合回到起点
            {
                float dist = Dist({lastX, lastY}, contour[0]);
                float e = CalcE(dist, params.lineWidth, lh, params.filamentDiameter);
                totalE += e;
                ss << "G1 X" << contour[0].x << " Y" << contour[0].y
                   << " E" << totalE << " F" << (int)(speed * 60) << "\n";
                lastX = contour[0].x;
                lastY = contour[0].y;
            }

            // 回抽
            if (params.retractionEnable)
            {
                totalE -= params.retractionAmount;
                ss << "G1 E" << totalE << " F" << (int)(params.retractionSpeed * 60) << "\n";
            }
        }

        // ── 打印内壁 ──
        for (const auto& contour : layer.innerContours)
        {
            if (contour.empty()) continue;
            ss << "G0 X" << contour[0].x << " Y" << contour[0].y
               << " F" << (int)(params.speedTravel * 60) << "\n";

            lastX = contour[0].x; lastY = contour[0].y;

            for (size_t i = 1; i < contour.size(); ++i)
            {
                float dist = Dist({lastX, lastY}, contour[i]);
                totalE += CalcE(dist, params.lineWidth, lh, params.filamentDiameter);
                ss << "G1 X" << contour[i].x << " Y" << contour[i].y
                   << " E" << totalE << " F" << (int)(speed * 60) << "\n";
                lastX = contour[i].x; lastY = contour[i].y;
            }
        }

        // ── 打印填充 ──
        for (const auto& seg : layer.infillLines)
        {
            // 快速移到起点
            ss << "G0 X" << seg.a.x << " Y" << seg.a.y
               << " F" << (int)(params.speedTravel * 60) << "\n";

            float dist = Dist(seg.a, seg.b);
            totalE += CalcE(dist, params.lineWidth, lh, params.filamentDiameter);

            ss << "G1 X" << seg.b.x << " Y" << seg.b.y
               << " E" << totalE << " F" << (int)(speed * 60) << "\n";
        }
    }

    // ── 尾部 ──
    ss << "\n; END\n";
    ss << "M104 S0 ; turn off nozzle\n";
    ss << "M140 S0 ; turn off bed\n";
    ss << "M106 S0 ; turn off fan\n";
    ss << "G28 X Y ; home XY\n";
    ss << "M84 ; disable motors\n";

    return ss.str();
}

} // namespace fdm
